version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # Algolia
  ALGOLIA_APP_ID: app_id
  ALGOLIA_API_KEY: api_key
  ALGOLIA_INDEX_NAME: index_name
  # Airtable
  AIRTABLE_ACCESS_TOKEN: token
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Chroma
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # DuckDB
  DUCKDB_DATABASE: database
  DUCKDB_SCHEMA: main
  # Google
  GOOGLE_SERVICE_ACC_KEY:
    type: service_account
    project_id: "final-project-455110"
    private_key_id: "e843378b5810f5812080620caf9c4711d5fba77f"
    private_key:  "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDRV5WTV2c6AE3z\nOWgb+ZBxqYAZ82TNptGhiFo5K+pOY7WAwjVBnKxAqnjiiIa2YzNQf2YtlH+tXBkV\nVRNOI/PzCeQ4Njg9yXmttRUTz/lN/R3jBu60zQaQpfF7MqSPHeGX452YpiSdVcRR\nwc/JS5wCjBGfGGYulxOnimfH7Axm9SpJNct0N+6RT1WLmQ9ZmNBXLZFlYehosFr2\nzWQ/qd295nJER4D7xYp/9zXPIqe1/HU2wlqO4bkJhfvCPRpLmHtra2b9l+iabwxt\nXmEj3V6gqJvHnrNf0U+wAh+EaV5N06Y9hQOc9OEZ7mjvAlQ5287E1My3pMyMIK2J\nhyDDKAbNAgMBAAECggEADp4M242qr2xC4JGbLdV1aLOB7WA+Iz6STrMJGuZL96EA\nuZtV+F1PQBZnMsR/JLTZaf8ZDGRK0gI5lHB2MDOdnq/U190d6jqP+BS33ei4Kwaj\nby064zS+UC5/SkHwlRLaEeW/SYRmGK3ImD+3PibhjStoo5W0/f75uoBwkmq3y4yB\nKFV0NpZz/TuTZTJzybl+TXLT2+PLHx5vLRsmNVIOWrd6BvYBo2kFXbxhftVHxdc+\nz0tdJ6mNgjEXGVFtFVgi1PrghUuDTtzTOXLc1jaN/GllU+PKFD3n1VE97DAn4i3U\nU672JZ16fL88/+rC4luM/yXo7s1CWVbHVMQBbOFhRQKBgQDnmqaVCrF9TrzaQroe\n23FqIwvcaT43CW4Wti5j7b6jNh0KvDe86Z/ns9os6xcCcq41ZdLKtrcHYwTiquO+\n8JsnAslf88u3+rslNBS1qPw7ftAiHClC55sxQByrg5tCYJJaYepHVbLhm65tpbf9\nMTtb10td89JtU7Od6xFy/lrB4wKBgQDnZKAbxfn8qXFFzO9pSUvxq8sAz4A8ng8Y\nSJQji5zQ0fWvYofI2cKfX9z73DniSgig7wwJDc7NmphUbFP40Fw41KZa4NBiQ3yD\n9XT0BmK6e2VYN10pgEKMxE8dX1XSNULJVOtPU4/lXQ0xMKQlgIrwdI4KFbwK489k\n4nNh6MyzjwKBgGLDXSQTckq4R+pfKBU+iOe02Dr+mixIFi0TNUchu/jHe6z3RGGH\n0suws2oSOjauBsH4kOIm9nfs7slmDEaBPfhtxMfpI8dp4WJlCivJSv5n/oN9NM82\nCsT+zPsK3St6GQ730DrpPaXdiI1zbLlIxEJO1fHTprk+R0shUciS1Mr3AoGAG681\nXL1OEIWxULmZN06WsH5uVlV9MUNz6OLeHnaYt383VtmCB2zOVUUh6lxJ7KIQ8DhJ\nh1fIk17YtNkVHuLG9eGzWZImPGt4nU0jxgJxk4Ap+uj803dN/wuJr6j1WqYWrIHl\neWM1Bysf5e+84+PCO8ymJdy918uzx400YtV4kE8CgYEAiB8xOhhzR0o0iNdxsz2K\nIvaR0LCuk6AjRqAT/+e6TZbohwBUUDcXGteFNOryuRMaw1K3qf+cwfDK7UXlehPx\nvSZGOFw5UW4jmxmBTm/IfDHSZKYafOa4WiuSB00OXc0sR4U0T00CJndvjt8+eECH\nsX58dWocVXwuCwxfjYENFNg=\n-----END PRIVATE KEY-----\n"
    client_email: "uber-engineering-project@final-project-455110.iam.gserviceaccount.com"
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/uber-engineering-project%40final-project-455110.iam.gserviceaccount.com"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/path/to/your/service/account/key.json"
  GOOGLE_LOCATION: US # Optional
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # Pinot
  PINOT_HOST: hostname
  PINOT_PASSWORD: password
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: user
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # Qdrant
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
  # Weaviate
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INSTANCE_API_KEY: YOUR-WEAVIATE-API-KEY
  WEAVIATE_INFERENCE_API_KEY: YOUR-OPENAI-API-KEY
  WEAVIATE_COLLECTION: collectionn_name
